"""Reconcile the Databricks contract tables with Project 1's DuckDB gold over the analysis window.

Pass criteria (spec 4.3): equal fact_sales rows and Σ units; baselines within 0.01 where both
exist; baseline NULL mismatches ≤ 0.1% (they can only come from the sliced history changing an
item's first sale); stock-out flag sets with Jaccard ≥ 0.999.

    python scripts/reconcile.py --export data/export --flagship ../Flagship/data/full/gold
"""
import argparse
import sys
from dataclasses import dataclass
from datetime import date
from pathlib import Path

import duckdb


@dataclass(frozen=True)
class Check:
    name: str
    value: str
    passed: bool
    detail: str


def _parquet(root: Path, table: str) -> str:
    """Spark exports a folder of part files; Project 1 writes one file per table."""
    folder = Path(root) / table
    path = folder / "*.parquet" if folder.is_dir() else Path(root) / f"{table}.parquet"
    return f"read_parquet('{path.as_posix()}')"


def reconcile(export_dir: Path, flagship_gold: Path, start: date, end: date) -> list[Check]:
    con = duckdb.connect()
    k0, k1 = int(start.strftime("%Y%m%d")), int(end.strftime("%Y%m%d"))
    for alias, root in (("dbx", export_dir), ("p1", flagship_gold)):
        for table in ("fact_sales", "fact_stockout_risk"):
            con.execute(f"CREATE VIEW {alias}_{table} AS SELECT * FROM {_parquet(root, table)} "
                        f"WHERE date_key BETWEEN {k0} AND {k1}")
    one = lambda q: con.execute(q).fetchone()  # noqa: E731

    rows_d, units_d = one("SELECT count(*), coalesce(sum(units), 0) FROM dbx_fact_sales")
    rows_p, units_p = one("SELECT count(*), coalesce(sum(units), 0) FROM p1_fact_sales")
    drift, mismatched, with_baseline = one("""
        SELECT
            count(*) FILTER (WHERE abs(d.baseline_units - p.baseline_units) > 0.01),
            count(*) FILTER (WHERE (d.baseline_units IS NULL) <> (p.baseline_units IS NULL)),
            count(*) FILTER (WHERE d.baseline_units IS NOT NULL OR p.baseline_units IS NOT NULL)
        FROM dbx_fact_sales AS d
        JOIN p1_fact_sales AS p USING (date_key, store_key, item_key)""")
    both, union = one("""
        SELECT count(*) FILTER (WHERE d.date_key IS NOT NULL AND p.date_key IS NOT NULL), count(*)
        FROM dbx_fact_stockout_risk AS d
        FULL JOIN p1_fact_stockout_risk AS p USING (date_key, store_key, item_key)""")
    null_share = mismatched / with_baseline if with_baseline else 0.0
    jaccard = both / union if union else 1.0
    return [
        Check("fact_sales rows", f"{rows_d:,} = {rows_p:,}" if rows_d == rows_p else f"{rows_d:,} ≠ {rows_p:,}",
              rows_d == rows_p and rows_d > 0, "Databricks vs Project 1, analysis window only"),
        Check("fact_sales Σ units", f"{units_d:,.2f} vs {units_p:,.2f}",
              abs(units_d - units_p) <= 1e-6 * max(1.0, abs(units_p)), "relative tolerance 1e-6"),
        Check("baseline_units within 0.01", f"{drift:,} rows differ", drift == 0,
              "rows where both tables have a baseline"),
        Check("baseline NULL mismatches ≤ 0.1%", f"{mismatched:,} of {with_baseline:,} ({null_share:.3%})",
              null_share <= 0.001, "only the sliced history (a later first sale) may cause these"),
        Check("stock-out flags Jaccard ≥ 0.999", f"{jaccard:.4f}", jaccard >= 0.999,
              f"{both:,} flags in both, {union - both:,} in only one"),
    ]


def write_report(checks: list[Check], path: Path, start: date, end: date) -> None:
    lines = [
        "# Reconciliation: Databricks vs Project 1",
        "",
        f"Contract tables compared over the analysis window {start} → {end}. Generated by `scripts/reconcile.py`.",
        "",
        "| Check | Result | Status | Note |",
        "|---|---|---|---|",
        *(f"| {c.name} | {c.value} | {'PASS' if c.passed else 'FAIL'} | {c.detail} |" for c in checks),
        "",
    ]
    Path(path).write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--export", type=Path, default=Path("data/export"), help="Parquet from notebook 07")
    parser.add_argument("--flagship", type=Path, required=True, help="Project 1 data/full/gold")
    parser.add_argument("--start", type=date.fromisoformat, default=date(2016, 8, 16))
    parser.add_argument("--end", type=date.fromisoformat, default=date(2017, 8, 15))
    parser.add_argument("--out", type=Path, default=Path("docs/reconciliation.md"))
    args = parser.parse_args()
    checks = reconcile(args.export, args.flagship, args.start, args.end)
    write_report(checks, args.out, args.start, args.end)
    for c in checks:
        print(f"{'PASS' if c.passed else 'FAIL'}  {c.name}: {c.value}")
    sys.exit(0 if all(c.passed for c in checks) else 1)


if __name__ == "__main__":
    main()
